name: Generate Snake

on:
  schedule:
    # Executa todo dia às 21h UTC
    - cron: "0 21 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: Jhonatas-de-Freitas  # Substitua por seu nome de usuário
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
